/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherdisplay;

import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.JSONException;
import weathermodel.CurrentWeatherData;
import weathermodel.WeatherSearchResult;
import weatherservice.OpenWeatherClient;

/**
 *
 * @author yudai
 */
public class DisplayFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisplayFrame
     */
    public DisplayFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    finderPanel = new javax.swing.JPanel();
    searchPanel = new javax.swing.JPanel();
    searchField = new javax.swing.JTextField();
    searchButton = new javax.swing.JButton();
    searchResultScrollPane = new javax.swing.JScrollPane();
    searchResultPanel = new javax.swing.JPanel();
    weatherPanel = new javax.swing.JPanel();
    forecastScrollPane = new javax.swing.JScrollPane();
    forecastListPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Weather Forecast App");
    setResizable(false);

    searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

    searchField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchFieldActionPerformed(evt);
      }
    });

    searchButton.setText("Search!");
    searchButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
    searchPanel.setLayout(searchPanelLayout);
    searchPanelLayout.setHorizontalGroup(
      searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(searchPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(searchField)
          .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        .addContainerGap())
    );
    searchPanelLayout.setVerticalGroup(
      searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(searchPanelLayout.createSequentialGroup()
        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(searchButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    searchResultScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Result"));
    searchResultScrollPane.setToolTipText("");
    searchResultScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    searchResultPanel.setLayout(new java.awt.GridBagLayout());
    searchResultScrollPane.setViewportView(searchResultPanel);

    javax.swing.GroupLayout finderPanelLayout = new javax.swing.GroupLayout(finderPanel);
    finderPanel.setLayout(finderPanelLayout);
    finderPanelLayout.setHorizontalGroup(
      finderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finderPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(finderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(searchResultScrollPane))
        .addContainerGap())
    );
    finderPanelLayout.setVerticalGroup(
      finderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(finderPanelLayout.createSequentialGroup()
        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(searchResultScrollPane))
    );

    weatherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Weather Forecast"));

    forecastScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Forecast"));

    forecastListPanel.setLayout(new java.awt.GridBagLayout());
    forecastScrollPane.setViewportView(forecastListPanel);

    javax.swing.GroupLayout weatherPanelLayout = new javax.swing.GroupLayout(weatherPanel);
    weatherPanel.setLayout(weatherPanelLayout);
    weatherPanelLayout.setHorizontalGroup(
      weatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(forecastScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
    );
    weatherPanelLayout.setVerticalGroup(
      weatherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weatherPanelLayout.createSequentialGroup()
        .addGap(0, 357, Short.MAX_VALUE)
        .addComponent(forecastScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(finderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(weatherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(finderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(weatherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_searchFieldActionPerformed

  private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    searchResultPanel.removeAll();  
    try {
        WeatherSearchResult result = client.getSearch(searchField.getText());
        ArrayList<CurrentWeatherData> resultData = result.getCityWeatherSearchResult();
        int size = result.getCityWeatherSearchResult().size();
        for (CurrentWeatherData data: resultData) {
          JPanel newPanel = new ResultPanel(data);
          // gbc untuk panel search biar rapi
          GridBagConstraints gbc = new GridBagConstraints();
          gbc.gridx = 0;
          gbc.weightx = 1.0;
          gbc.anchor = GridBagConstraints.NORTH;
          gbc.fill = GridBagConstraints.HORIZONTAL;
          searchResultPanel.add(newPanel, gbc);
        }
        // biar semua hasilnya naik ke atas
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = size-1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        searchResultPanel.add(new JLabel(" "), gbc);  // blank JLabel
        searchResultPanel.repaint();
        searchResultPanel.revalidate();
        //TODO: Tambahin handler forecast untuk weatherPanel
        for (int i=0; i<30; i++) {
          ForecastPanel forecastPanel = new ForecastPanel();
          GridBagConstraints anothergbc = new GridBagConstraints();
          gbc.gridy = 0;
          gbc.weighty = 1.0;
          forecastListPanel.add(forecastPanel);
        }
        forecastListPanel.repaint();
        forecastListPanel.revalidate();
      } catch (JSONException ex) {
        Logger.getLogger(DisplayFrame.class.getName()).log(Level.SEVERE, null, ex);
        return;
      }
  }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayFrame().setVisible(true);
            }
        });
    }
  private static final String KEY = "1410697d3b7d76e4d1a16c890195cc57";  
  // Open Weather Client declaration
  private OpenWeatherClient client = new OpenWeatherClient(KEY);
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel finderPanel;
  private javax.swing.JPanel forecastListPanel;
  private javax.swing.JScrollPane forecastScrollPane;
  private javax.swing.JButton searchButton;
  private javax.swing.JTextField searchField;
  private javax.swing.JPanel searchPanel;
  private javax.swing.JPanel searchResultPanel;
  private javax.swing.JScrollPane searchResultScrollPane;
  private javax.swing.JPanel weatherPanel;
  // End of variables declaration//GEN-END:variables
}
