/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherdisplay;

import javax.swing.JPanel;
import util.Formatter;
import weathermodel.ForecastData;

/**
 *
 * @author yudai
 */
public class ForecastPanel extends javax.swing.JPanel {

  /**
   * Creates new form ForecastPanel
   */
  public ForecastPanel(ForecastData forecast) {
    initComponents();
    // assign everything to label
    dateTimeLabel.setText(forecast.getDateTimeText());
    weatherDetailLabel.setText(Formatter.capitalizeFully(forecast.getWeatherDetails()));
    maxTempLabel.setText(Formatter.toCelcius(String.valueOf(forecast.getTempMax())));
    minTempLabel.setText(Formatter.toCelcius(String.valueOf(forecast.getTempMin())));
    humidityLabel.setText(Formatter.toPercent(String.valueOf(forecast.getHumidity())));
    cloudinessLabel.setText(Formatter.toPercent(String.valueOf(forecast.getCloudiness())));
    windSpeedLabel.setText(Formatter.toMPS(String.valueOf(forecast.getWindSpeed())));
    windDirectionLabel.setText(Formatter.toDegree(String.valueOf(forecast.getWindDeg())));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dateTimeLabel = new javax.swing.JLabel();
    weatherDetailLabel = new javax.swing.JLabel();
    maxTempLabel = new javax.swing.JLabel();
    minTempLabel = new javax.swing.JLabel();
    humidityLabel = new javax.swing.JLabel();
    cloudinessLabel = new javax.swing.JLabel();
    windLabel = new javax.swing.JLabel();
    windSpeedLabel = new javax.swing.JLabel();
    windDirectionLabel = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());
    setPreferredSize(new java.awt.Dimension(190, 360));

    dateTimeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    dateTimeLabel.setText("2018-01-01-18:00:00");

    weatherDetailLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    weatherDetailLabel.setText("Cuaca");

    maxTempLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    maxTempLabel.setText("Max. Temp: 30 C");

    minTempLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    minTempLabel.setText("Min. Temp : 29 C");

    humidityLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    humidityLabel.setText("Humidity: 100%");

    cloudinessLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    cloudinessLabel.setText("Cloudiness: 100%");

    windLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    windLabel.setText("Wind");

    windSpeedLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    windSpeedLabel.setText("Speed: 30.5005 m/s");

    windDirectionLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    windDirectionLabel.setText("Direction: SE");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(dateTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
          .addComponent(maxTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(humidityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(minTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(windDirectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(windSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cloudinessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(weatherDetailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(windLabel)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(weatherDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(maxTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(minTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(humidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cloudinessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(windLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(windSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(windDirectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(23, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel cloudinessLabel;
  private javax.swing.JLabel dateTimeLabel;
  private javax.swing.JLabel humidityLabel;
  private javax.swing.JLabel maxTempLabel;
  private javax.swing.JLabel minTempLabel;
  private javax.swing.JLabel weatherDetailLabel;
  private javax.swing.JLabel windDirectionLabel;
  private javax.swing.JLabel windLabel;
  private javax.swing.JLabel windSpeedLabel;
  // End of variables declaration//GEN-END:variables
}
